name = "TensND"
uuid = "474b5345-2588-4284-8a58-2430a1a40cb0"
authors = ["Jean-François Barthélémy"]
version = "0.1.5"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
OMEinsum = "ebe7aa44-baf0-506c-a96f-8464559b3922"
Rotations = "6038ab10-8711-5258-84ad-4b1120ba62dc"
SymPy = "24249f21-da20-56a4-8eb1-6a02cf4ae2e6"
Symbolics = "0c5d862f-8b57-4792-8d23-62f2024744c7"
Tensors = "48a634ad-e948-5137-8d70-aa71f2a747f4"
TimerOutputs = "a759f4b9-e2f1-59dc-863e-4aeb61b1ea8f"

[compat]
OMEinsum = "0.9"
Rotations = "1"
SymPy = "2"
Symbolics = "6, 7"
Tensors = "1"
TimerOutputs = "0.5"
julia = "1.12"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
